### ISSUE TITLE
Feat(QuestFactory): Emit project name on QuestCreation

### ISSUE THREAD

**Issue by Quazia** [rabbitholegg/quest-protocol#258]
- [ ] [Add Project name, Quest name, action type, and action network to `QuestCreation` event](https://github.com/rabbitholegg/quest-protocol/blob/main/contracts/QuestFactory.sol#L715)
- [ ] Add Project Name to `createERC20QuestInternal` and `createERC1155QuestInternal` params

**Comment by pntemi** [comment]
Can we also add the following fields as well?
- quest_name
- action_type
- action_network

I understand that we have these fields in the `QuestClaimedData` event, and we shouldn't remove them from there as discussed during the sidebar. However, it's weird that we are in a state where no event has a complete information about the quest at all, and we have to do a join every time we want the data.

Since we're making the change to `QuestCreated` event, let's add them now.

**Comment by Quazia** [comment]
Updated the issue!
